export { default as ChangePassword } from "./ChangePassword";
export { default as CourseDetail } from "./CourseDetail";
export { default as Courses } from "./Courses";
export { default as EnrollFail } from "./EnrollFail";
export { default as EnrollSuccess } from "./EnrollSuccess";
export { default as HomePage } from "./HomePage";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as UserProfile } from "./UserProfile";
